### ISSUE TITLE
Improve definition of Model Traits/Domain Roles

### ISSUE THREAD

**Issue by Nagelfar** [Softwarepark/Contexture#39]
At the moment model traits are defined as a single free-text value. Some suggestions are available but need to be copied manually into the text field.

As a first step model traits should be renamed to the more expressive domain roles.
And a  bounded context can have multiple roles, so domain roles should capture a list of roles instead of the single text field.
One role can be either: 
- selected from the predefined list
- entered with a name and a description

A role should only be added once to the bounded context

**Comment by grede** [comment]
@Nagelfar do we have a predefined list of roles somewhere already? How is it going to be populated ?

**Comment by Nagelfar** [comment]
At the moment we have [this list](https://github.com/ddd-crew/bounded-context-canvas/blob/master/resources/model-traits-worksheet.md) hardcoded [here](https://github.com/Softwarepark/Contexture/blob/master/app/src/Page/Bcc/Edit.elm#L448).

The list can be used for the roles & hardcoding should be good enough for now
